### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#11]
No an issue really, but a question. Do you have intention to release package on CRAN?
If so what is the plan? what help is needed (if any)?

**Comment by wrathematics** [comment]
I hope to get the package on CRAN pretty soon. I was having a bunch of problems with Windows that took a lot of effort to fix, but they should all be good now. I expect to have a bit of back and forth with CRAN during submission, but ideally it will be published by the end of the week.

**Comment by dselivanov** [comment]
I have couple of things in my mind. Mb worth to think about them before initial release:

1. Internal structure of float matrices. Now it is S4 object with "integer" matrix. Mb it worth to adapt format to look like [Matrix::dgeMatrix](https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/dgeMatrix-class.html). And mb call it something like "fgeMatrix" or "sgeMatrix". So it will be more consistent with base R (I think `Matrix` package can be considered as base). May be I'm wrong - will be happy to discuss.
1. Is size of integer always equal to float?

Will try add more if I will remember.

**Comment by wrathematics** [comment]
I actually already submitted to CRAN around this time yesterday. Although I haven't heard back from them yet, so no telling what that means.

The naming isn't a bad idea, but I'm not sure about changing at this point. Matrix's naming tries to mimic LAPACK's, so an `sgeMatrix` would make sense. I went with `float`/`float32` because I view the package as more of an extension to the base package (and the `double` type) than the Matrix package, and because every other language uses something similar. I think if I ever got around to handling sparse floats, I'd do `sgCMatrix`.

The package assumes IEEE 754 compliance which guarantees that `sizeof(float)` is always 4. However, `sizeof(int)` is not guaranteed to be 4; it's up to the compiler. At the moment, the package configure tests for the size of `int` and errors before compilation if it's not 4. Eventually I plan to add a secondary backend (the external pointer from before) with an in-place interface for less memory consumption when iterating. But no clue when I'll get to that.

**Comment by dselivanov** [comment]
However as I remember R guarantee that integers in R are always 4 bytes.

28 нояб. 2017 г. 22:03 пользователь "Drew Schmidt" <notifications@github.com>
написал:

**Comment by snoweye** [comment]
No need to worry size of int. Some professors may use funny compilers. Just make sure enough space (can be any) to hold the data in float with the right length saved in the S4 object.

**Comment by wrathematics** [comment]
After one minor revision, it's on CRAN https://cran.r-project.org/web/packages/float/index.html

There's still time for Solaris to break and ruin my day, but hopefully everything's good.

**Comment by dselivanov** [comment]
@wrathematics any plans to upload updated pkg to CRAN? Do you have something special in mind before new release?

**Comment by wrathematics** [comment]
I plan to update it soon, but I have some other packages I have to update first (or they'll get kicked off of cran 😆)

**Comment by dselivanov** [comment]
@wrathematics same question :-) any plans to update CRAN version to 0.2-2? I want to finally push `rsparse` to CRAN and 0.2-2 will help with linking on OS X and I expect everything should work smoothly on all platforms.

**Comment by wrathematics** [comment]
I'm still trying to find a better way to test on OSX. I have a very old mac, but it's configured very strangely or something. Give me a few more days and I'll try to update it this weekend.

**Comment by wrathematics** [comment]
I'm waiting on another package to clear CRAN submission. Once that's done, I'm submitting the new float, hopefully tonight or tomorrow.

**Comment by wrathematics** [comment]
As usual, everything with me took way longer than it should have. But I submitted it this morning and it's passed the pre-check with no issues, so hopefully everything populates within a day or so without incident.
