### ISSUE TITLE
Using Rcpp?

### ISSUE THREAD

**Issue by cdeterman** [wrathematics/float#15]
This is a particularly interesting package to me.  I just glanced through the vignette and the section 'For Developers'.  In it you are referring to the use of `.Call()` which it appears is the primary use in the package.  From a development standpoint, have you tried to use `Rcpp` in any capacity to simplify your internal code?

**Comment by wrathematics** [comment]
I've used Rcpp in the past, but I generally don't use it anymore.

**Comment by cdeterman** [comment]
Was this because of a limitation or conflict?  Or is it just a preference on your part?  I simply want to make sure I understand the internals and how they are written as I explore this package.

**Comment by wrathematics** [comment]
It's essentially personal preference. I tend to write C99 instead of C++, especially when I need to interface directly with Fortran as here. I'm also not fond of the compile times that Rcpp adds, and not using Rcpp avoids a dependency. The package builds with just R installed, which I think is nice.
