### ISSUE TITLE
Note: no visible binding for '<<-'

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/float#8]
After package installation:

> Note: no visible binding for '<<-' assignment to 'NA_float_' 
> Note: no visible binding for '<<-' assignment to '.Machine_float' 

Quick googling points to [this thread](https://stackoverflow.com/questions/24258770/using-compiler-package-and-suppress-no-visible-binding-for-global-variable)

**Comment by wrathematics** [comment]
Yeah, so far I've been ignoring those messages since they don't show up in R CMD check. Even after reading that thread, I'm still not sure what (if anything?) to do about them.

Basically they're global variables set by `.onLoad()` in `R/zzz.r` to mimic `NA_real_` and the like plus `.Machine`. I tried declaring them with `utils::globalVariables()` but it still complains.

**Comment by dselivanov** [comment]
I think we can close. Since the issue doesn't bother CRAN, we should not worry :-)
